# Generated by Django 2.1 on 2019-02-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('details', models.TextField(max_length=500, null=True)),
                ('occurenceDate', models.DateTimeField(max_length=50, null=True)),
                ('image', models.FileField(max_length=200, null=True, upload_to='')),
            ],
        ),
    ]
